copyright: Copyright &copy; {{copyright_year}} {{cookiecutter.author}}.
dev_addr: 127.0.0.1:8001
docs_dir: docs/src
edit_uri: 'blob/develop/docs/'
repo_url: https://github.com/{{cookiecutter.github_user}}/{{cookiecutter.github_repo}}
site_author: {{cookiecutter.author}}
site_description: ""
site_dir: ./~build/docs
site_name: {{cookiecutter.project_title}}
site_url: https://unicef.github.io/{{cookiecutter.github_user}}/{{cookiecutter.github_repo}}/
strict: false
exclude_docs: |
  _docs/*
  _hooks/*
  _includes/*
  _scripts/*
  ~*

markdown_extensions:
  - admonition
  - pymdownx.magiclink
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

theme:
  name: "material"
  color_mode: auto
  custom_dir: docs/_theme/overrides
  favicon: img/favicon.ico
  logo: img/logo.png
  user_color_mode_toggle: true
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - header.autohidex
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
  extra:
    version:
      provider: mike
      alias: true
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: light blue
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: light blue
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - mkdocstrings:
      default_handler: python
  - awesome-pages
  - search
  - gen-files:
      scripts:
        - docs/_scripts/copy_logos.py
        - docs/_scripts/get_settings.py
watch:
  - src/

hooks:
  - docs/_hooks/hooks.py
